builds:
  - id: cli-darwin-amd64
    main: ./cmd/cli
    binary: go-gopher-cli
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X github.com/Git-Gopher/go-gopher/version.Version={{.Version}} -X github.com/Git-Gopher/go-gopher/version.CommitHash={{.Commit}} -X github.com/Git-Gopher/go-gopher/version.CompileDate={{.Date}}
  - id: marker-darwin-amd64
    main: ./cmd/marker
    binary: go-gopher-marker
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X github.com/Git-Gopher/go-gopher/version.Version={{.Version}} -X github.com/Git-Gopher/go-gopher/version.CommitHash={{.Commit}} -X github.com/Git-Gopher/go-gopher/version.CompileDate={{.Date}}
  - id: cli-linux-amd64
    main: ./cmd/cli
    binary: go-gopher-cli
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=gcc
      - CXX=g++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X github.com/Git-Gopher/go-gopher/version.Version={{.Version}} -X github.com/Git-Gopher/go-gopher/version.CommitHash={{.Commit}} -X github.com/Git-Gopher/go-gopher/version.CompileDate={{.Date}}
  - id: marker-linux-amd64
    main: ./cmd/marker
    binary: go-gopher-marker
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=gcc
      - CXX=g++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X github.com/Git-Gopher/go-gopher/version.Version={{.Version}} -X github.com/Git-Gopher/go-gopher/version.CommitHash={{.Commit}} -X github.com/Git-Gopher/go-gopher/version.CompileDate={{.Date}}
  - id: cli-windows-amd64
    main: ./cmd/cli
    binary: go-gopher-cli
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X github.com/Git-Gopher/go-gopher/version.Version={{.Version}} -X github.com/Git-Gopher/go-gopher/version.CommitHash={{.Commit}} -X github.com/Git-Gopher/go-gopher/version.CompileDate={{.Date}}
  - id: marker-windows-amd64
    main: ./cmd/marker
    binary: go-gopher-marker
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X github.com/Git-Gopher/go-gopher/version.Version={{.Version}} -X github.com/Git-Gopher/go-gopher/version.CommitHash={{.Commit}} -X github.com/Git-Gopher/go-gopher/version.CompileDate={{.Date}}
archives:
  - id: golang-cross
    builds:
      - main-darwin-amd64
      - cli-darwin-amd64
      - marker-darwin-amd64
      - main-linux-amd64
      - cli-linux-amd64
      - marker-linux-amd64
      - main-windows-amd64
      - cli-windows-amd64
      - marker-windows-amd64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'