#!/bin/bash

# download all student repos and set them up so that all branches are downloaded
mkdir quick-draw-beta-final-team-01 && cd quick-draw-beta-final-team-01 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-01 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-02 && cd quick-draw-beta-final-team-02 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-02 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-03 && cd quick-draw-beta-final-team-03 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-03 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-04 && cd quick-draw-beta-final-team-04 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-04 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-05 && cd quick-draw-beta-final-team-05 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-5 .git && git config --bool core.bare false && git reset --hard && cd .. # actual repo has name error!
mkdir quick-draw-beta-final-team-06 && cd quick-draw-beta-final-team-06 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-06 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-07 && cd quick-draw-beta-final-team-07 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-07 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-08 && cd quick-draw-beta-final-team-08 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-08 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-09 && cd quick-draw-beta-final-team-09 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-09 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-10 && cd quick-draw-beta-final-team-10 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-10 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-11 && cd quick-draw-beta-final-team-11 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-11 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-12 && cd quick-draw-beta-final-team-12 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-12 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-13 && cd quick-draw-beta-final-team-13 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-13 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-14 && cd quick-draw-beta-final-team-14 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-14 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-15 && cd quick-draw-beta-final-team-15 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-15 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-16 && cd quick-draw-beta-final-team-16 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-16 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-17 && cd quick-draw-beta-final-team-17 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-17 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-18 && cd quick-draw-beta-final-team-18 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-18 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-19 && cd quick-draw-beta-final-team-19 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-19 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-20 && cd quick-draw-beta-final-team-20 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-20 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-21 && cd quick-draw-beta-final-team-21 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-21 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-22 && cd quick-draw-beta-final-team-22 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-22 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-23 && cd quick-draw-beta-final-team-23 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-23 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-24 && cd quick-draw-beta-final-team-24 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-24 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-25 && cd quick-draw-beta-final-team-25 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-25 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-26 && cd quick-draw-beta-final-team-26 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-26 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-27 && cd quick-draw-beta-final-team-27 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-27 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-28 && cd quick-draw-beta-final-team-28 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-28 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-29 && cd quick-draw-beta-final-team-29 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-29 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-30 && cd quick-draw-beta-final-team-30 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-30 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-31 && cd quick-draw-beta-final-team-31 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-31 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-32 && cd quick-draw-beta-final-team-32 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-32 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-33 && cd quick-draw-beta-final-team-33 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-33 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-34 && cd quick-draw-beta-final-team-34 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-34 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-35 && cd quick-draw-beta-final-team-35 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-35 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-36 && cd quick-draw-beta-final-team-36 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-36 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-37 && cd quick-draw-beta-final-team-37 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-37 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-38 && cd quick-draw-beta-final-team-38 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-38 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-39 && cd quick-draw-beta-final-team-39 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-39 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-40 && cd quick-draw-beta-final-team-40 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-40 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-41 && cd quick-draw-beta-final-team-41 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-41 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-42 && cd quick-draw-beta-final-team-42 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-42 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-43 && cd quick-draw-beta-final-team-43 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-43 .git && git config --bool core.bare false && git reset --hard && cd ..
mkdir quick-draw-beta-final-team-44 && cd quick-draw-beta-final-team-44 && git clone --mirror https://github.com/SOFTENG206-2022/quick-draw-beta-final-team-44 .git && git config --bool core.bare false && git reset --hard && cd ..
