name: check
on:
  pull_request:
    branches: main

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: make build
      - name: Run go vet
        run: go vet ./...
      - name: Run tests
        run: make test
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48.0
