name: git-gopher
on:
  pull_request:
    branches: main

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Cache
        uses: actions/cache@v3
        with:
          path: cache.json
          key: ${{ github.ref }}
      - name: Analyze Workflow
        uses: Git-Gopher/go-gopher-action@latest
        id: git-gopher
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_URL: ${{ github.server_url }}/${{ github.repository }}/
      - name: Add PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "${{ steps.git-gopher.outputs.pr_summary }}"
      - name: Artifact Log
        uses: actions/upload-artifact@v3
        with:
          path: log-**.json