name: git-gopher-test
on:
  pull_request:
    branches: main

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Verify dependencies
        run: go mod verify
      - name: Development Build
        run: make build
      - name: Run go vet
        run: go vet ./...
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
      - name: Run tests
        run: make test
      - name: Use Cache
        uses: actions/cache@v3
        with:
          path: cache.json
          key: ${{ github.ref }}
      - name: Analyze Workflow
        run: |
          chmod +x bin/go-gopher-github-action
          ./bin/go-gopher-github-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Artifact outputs
        uses: actions/upload-artifact@v3
        with:
          path: |
            log-**.json
            cache.json
