# Temporary file for a test.
name: git-gopher
on:
  pull_request:
    branches: main
jobs:
  git-gopher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Cache
        uses: actions/cache@v3
        with:
          path: cache.json
          key: ${{ github.ref }}
      - name: Analyze Workflow
        uses: Git-Gopher/go-gopher-action@test-comment-0
        id: git-gopher
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_URL: ${{ github.server_url }}/${{ github.repository }}/
      - name: Escape Comment
        id: escape-comment
        run: |
          text="${{ steps.git-gopher.outputs.pr_summary }}"
          echo "$text"
          text="${text//'%'/'%25'}"
          text="${text//$'\n'/'%0A'}"
          text="${text//$'\r'/'%0D'}"
          echo "$text"
          echo "::set-output name=pr_summary::$text"
      - name: Add PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "${{ steps.escape-comment.outputs.pr_summary }}"
