name: git-gopher-test
on:
  pull_request:
    branches: main

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: go build -v ./...
      - name: Run go vet
        run: go vet ./...
      - name: Run tests
        run: make test
      - name: Use Cache
        uses: actions/cache@v3
        with:
          path: cache.json
          key: ${{ github.ref }}
      - name: Analyze Workflow
        id: go-gopher
        run: |
          chmod +x ./go-gopher
          ./go-gopher action -l
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_URL: ${{ github.server_url }}/${{ github.repository }}/
      - name: Add PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "${{ steps.go-gopher.outputs.pr_summary }}"
      - name: Artifact Log
        uses: actions/upload-artifact@v3
        with:
          path: log-**.json
      - name: Dump event
        run: |
          echo ${{ github.event }}
