name: release
on:
  pull_request:
    branches: main

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: go build -o go-gopher -v ./cmd/github-action 
      - name: Run go vet
        run: go vet ./...
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
      - name: Run tests
        run: make test
      - name: Prerelease
        env:
          GITHUB_TOKEN: "${{ secrets.RELEASE_REPO_SECRET }}"
        run: |
          gh release delete ${GITHUB_REF##*/} --yes -R https://github.com/Git-Gopher/go-gopher-action || true
          gh release create ${GITHUB_REF##*/} go-gopher -R https://github.com/Git-Gopher/go-gopher-action --generate-notes