name: release
on:
  push:
    branches: main

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: go build -v
      - name: Run go vet
        run: go vet ./...
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
      - name: Run tests
        run: make test
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "go-gopher"
          files: |
            go-gopher