name: release
on:
  push:
    branches: main

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: make build -- -ldflags="-s -w"
      - name: Run go vet
        run: go vet ./...
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
      - name: Run tests
        run: make test
      - name: Run UPX
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          files: |
            bin/*
          args: -9v --ultra-brute
      - name: Release
        env:
          GITHUB_TOKEN: "${{ secrets.RELEASE_REPO_SECRET }}"
        run: |
          gh release delete latest --yes -R https://github.com/Git-Gopher/go-gopher-action || true
          gh release create latest bin/* -R https://github.com/Git-Gopher/go-gopher-action --generate-notes